// <auto-generated />
namespace BikeDistributor.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedcreatedatetimetonull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedcreatedatetimetonull));
        
        string IMigrationMetadata.Id
        {
            get { return "201712290017215_changed create date time to null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
